name: Resume ci Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build latest 
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Login to Docker hub
      run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
    - name: Tag image
      run:  docker tag my-image-name:${{github.run_number}} ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}
  deploy:
   needs: build 
   runs-on: ubuntu-latest
   steps:
    - name: SSH to Server 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 44.215.71.187
        username: ec2-user 
        key: ${{secrets.KEY}}
        script: |
          docker stop resume || echo ""
          docker remove resume || echo ""
          docker run -d --name resume port 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}

